[/Script/Engine.InputSettings]
DefaultPlayerInputClass=/Script/EnhancedInput.EnhancedPlayerInput
DefaultInputComponentClass=/Script/EnhancedInput.EnhancedInputComponent
bCaptureMouseOnLaunch=False
DefaultViewportMouseCaptureMode=NoCapture
DefaultViewportMouseLockMode=DoNotLock
+AxisMappings=(AxisName="MoveForward",Scale=1.000000,Key=Up)
+AxisMappings=(AxisName="MoveForward",Scale=-1.000000,Key=Down)
+ActionMappings=(ActionName="Sprint",Key=LeftShift)
+ActionMappings=(ActionName="Crouch",Key=LeftControl)
+ActionMappings=(ActionName="Interact",Key=E)
+AxisMappings=(AxisName="MoveRight",Scale=1.000000,Key=Right)
+AxisMappings=(AxisName="MoveRight",Scale=-1.000000,Key=Left)
+ActionMappings=(ActionName="Jump",Key=SpaceBar)
# Vehicle enter/exit while near the DeLorean.
+ActionMappings=(ActionName="ToggleVehicleHero",Key=G)
